package mod.upcraftlp.offhandtweaks.proxy;

import net.minecraftforge.fml.common.ModMetadata;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

import static mod.upcraftlp.offhandtweaks.Reference.*;

/**
 * @author UpcraftLP <b>CLIENT-ONLY</b>
 */
@SideOnly(Side.CLIENT)
public class ClientProxy extends CommonProxy {

    @Override
    public void preInit(FMLPreInitializationEvent event) {
        super.preInit(event);
        ModMetadata data = event.getModMetadata();
        data.autogenerated = false;
        data.authorList = authors;
        data.credits = CREDITS;
        data.description = MOD_DESCRIPTION;
        data.url = WEBSITE;
    }
}
